proxy:
  host: proxy
  port: 8100

s3:
  region: eu-central-1

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: secret
  db_name: postgres

kafka:
  url: kafka:29092

loki:
  url: http://loki:3100

data_bright:
  host: "brd.superproxy.io"
  port: 33335
  allow_domains:
    - "www.copart.ca"
    - "copart.ca"
    - "www.copart.com"
    - "copart.com"
    - "cs.copart.com"