copart:
  user: #replace
  password: #replace

proxy:
  host: localhost
  port: 8100

minio:
  url: http://localhost:9000
  user: root
  password: secret123

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: secret
  db_name: postgres

kafka:
  url: localhost:9092

loki:
  url: http://localhost:3100

data_bright:
  host: "brd.superproxy.io"
  port: 33335
  user: #replace
  password: #replace
  allow_domains:
    - "www.copart.ca"
    - "copart.ca"
    - "www.copart.com"
    - "copart.com"
    - "cs.copart.com"